- hosts: localhost
  tasks:
    - name: Python - install
      apt:
        pkg:
          - python3-full
          # symlink /usr/bin/python to /usr/bin/python3
          - python-is-python3
          - python3-virtualenvwrapper
