- hosts: localhost
  tasks:
    - name: C - install tools
      apt:
        pkg:
          - build-essential
          - gcc
          - gdb
          - gdb-doc
          - make
          - autoconf
          - automake
          - clang
          - clangd
          - bear # builds compilation database for clangd
          - universal-ctags

    - name: C - install common libraries
      apt:
        pkg:
          - libopenblas-dev
          - libpq-dev
          - default-libmysqlclient-dev
          - libpng-dev
