- hosts: localhost
  tasks:
    - name: Go - install
      apt:
        pkg:
          - golang
          - golang-go
          - golang-doc
          - golang-src
          - gopls # language server
