- hosts: localhost
  tasks:
    - name: C - install tools
      apt:
        pkg:
          - build-essential
          - gcc
          - gdb
          - gdb-doc
          - make
          - autoconf
          - automake
          - clang
          - clangd
          - bear # builds compilation database for clangd
          - universal-ctags

    - name: C - install common headers
          # many Python/Ruby/Node/etc packages will require some of those
          - libpq-dev
          - default-libmysqlclient-dev
          - libpng-dev
