- hosts: localhost
  tasks:
    - name: C - install tools
      apt:
        pkg:
          - build-essential
          - gdb
          - gdb-doc
          - make
          - autoconf
          - automake
          - universal-ctags

    - name: C - install common headers
          # many Python/Ruby/Node/etc packages will require some of those
          - libpng-dev
