- hosts: localhost
  tasks:
    - name: Python - install
      apt:
        pkg:
          - python3-pip

    - name: Python - packages
      pip:
        executable: pip3
        state: latest
        name:
          - virtualenv
          - jupyter
          - jupyterlab
          - numpy
          - scipy
          - pandas
          - matplotlib
          - csvkit
