- hosts: localhost
  tasks:
    - name: Install PostgreSQL
      apt:
        pkg:
          - postgresql
          - libpq-dev
          - pgcli

    - name: Install MySQL
      apt:
        pkg:
          - default-mysql-server
          - mycli

    - name: Install SQLite3
      apt:
        pkg:
          - sqlite3

    - name: Install Redis
      apt:
        pkg:
          - redis-server
          - redis-tools
