- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Allow Debian Unstable & Experimental packages only on demand
      copy:
        dest: /etc/apt/preferences.d/pins
        # That empty line makes or breaks the pins
        content: |
          Package: *
          Pin: release a=unstable
          Pin-Priority: 400

          Package: *
          Pin: release a=experimental
          Pin-Priority: 400

    - name: Debian Unstable repo
      apt_repository:
        repo: deb http://ftp.icm.edu.pl/pub/Linux/debian unstable main non-free non-free-firmware contrib

    - name: Debian Experimental repo
      apt_repository:
        repo: deb http://ftp.icm.edu.pl/pub/Linux/debian experimental main non-free non-free-firmware contrib

    - name: Install base system packages
      apt:
        pkg:
          # Base
          - linux-image-amd64
          - linux-headers-amd64
          - iw # wifi
          - network-manager # wifi
          - rcm # dotfiles
          - cups # printer
          # Desktop software
          - gnome-core
          - gnome-tweaks
          - gnome-shell-extensions
          - gnome-shell-extension-manager
          - foliate
          - gimp
          - keepassx
          # Themes
          - yaru-theme-gnome-shell
          - yaru-theme-gtk
          - papirus-icon-theme
          - breeze-cursor-theme
          # Fonts
          - fonts-ubuntu
          - fonts-paratype # PT Sans / PT Serif
          - fonts-lato
          - fonts-crosextra-caladea
          - fonts-crosextra-carlito
          - fonts-jetbrains-mono
          - fonts-firacode
          - fonts-inconsolata

    - name: Configure users
      with_items: "{{ users }}"
      user:
        name: "{{ item }}"
        state: present
        groups:
          - sudo
          - lp
          - lpadmin

    - name: Hardware clock in local time
      command: /usr/bin/timedatectl set-local-rtc 1

    - name: Locales - generate
      locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ locale_to_generate }}"

    - name: Locales - setup
      copy:
        dest: /etc/default/locale
        content: |
          LANG={{ locale_lang }}
          LC_TIME={{ locale_time }}

    - name: Chrome - setup apt key
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Chrome - setup apt repository
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main

    - name: Chrome - install
      apt:
        pkg: google-chrome-stable

    - name: Sysctl settings
      # Necessary for IDEs and editors (intellij etc.),
      # which use inotify to watch filesystem changes
      sysctl: name=fs.inotify.max_user_watches value=524288
