- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Install packages
      apt:
        pkg:
          # Base
          - iw # wifi
          - network-manager # wifi
          - rcm # dotfiles
          - ufw # firewall
          - cups # printer
          # Desktop
          - gnome-core
          - gnome-shell-extensions
          - gnome-tweak-tool
          - wl-clipboard
          - numix-gtk-theme
          - moka-icon-theme
          - fonts-ubuntu
          - fonts-firacode
          - fonts-inconsolata
          - fonts-crosextra-caladea
          - fonts-crosextra-carlito
          # Desktop software
          - gimp
          - keepassx

    - name: Add users to groups
      with_items: "{{ users }}"
      user:
        name: "{{ item }}"
        groups: sudo,lp,lpadmin
        append: yes

    - name: Locales - generate
      locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ locale }}"

    - name: Locales - setup
      copy:
        dest: /etc/default/locale
        content: |
          LANG={{ locale_lang }}
          LC_TIME={{ locale_time }}

    - name: X - cursor theme install
      apt: pkg=dmz-cursor-theme

    - name: X - cursor theme setup
      alternatives:
        name: x-cursor-theme
        path: /usr/share/icons/DMZ-White/index.theme

    - name: Chrome - setup apt key
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Chrome - setup apt repository
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main

    - name: Chrome - install
      apt:
        pkg: google-chrome-stable

    - name: Spotify - setup apt key
      apt_key:
        url: https://download.spotify.com/debian/pubkey.gpg
        state: present

    - name: Spotify - setup apt repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free

    - name: Spotify - install
      apt:
        pkg: spotify-client

    - name: Firewall
      ufw:
        state: enabled

    - name: Firewall - allow outgoing
      ufw:
        direction: outgoing
        policy: allow

    - name: Firewall - deny incoming
      ufw:
        direction: incoming
        policy: deny

    - name: Sysctl settings
      # Necessary for IDEs and editors (intellij etc.),
      # which use inotify to watch filesystem changes
      sysctl: name=fs.inotify.max_user_watches value=524288
