- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Install packages
      apt:
        pkg:
          # Base
          - tmux
          - neovim
          - git
          - tig
          - ripgrep
          - fd-find
          - fzf
          - jq
          - pv

          # Crypto
          - wireguard
          - openresolv # dependency of wireguard
          - openvpn
          - openssh-client
          - gnupg

          # DB clients
          - postgresql-client
          - default-mysql-client

          # HTTP clients
          - wget
          - curl

          # Cloud
          - rclone
          - awscli

          # Troubleshooting - general
          - sysstat # sar/pidstat/...
          - linux-perf
          - bpfcc-tools
          - strace
          - lsof
          - iftop
          - htop

          # Troubleshooting - network
          - tcpdump
          - wireshark
          - tshark
          - mtr
          - ngrep
          - nmap
          - ncat
          - socat
          - dnsutils # dig
          - net-tools # netstat
          - whois

    # pinentry-gnome3 uses a modal dialog, does not work with a password manager
    # pinentry-tty has this bug:
    # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850946
    # It is fixed in gpg 2.3, but gpg 2.3 is experimental and is not packaged in Debian/Ubuntu
    # When gpg 2.3 or 2.4 enters Debian, switch to pinentry-tty
    - name: GPG - install pinentry-qt
      apt:
        pkg: pinentry-qt

    - name: GPG - pinentry-qt as default pinentry
      alternatives:
        name: pinentry
        path: /usr/bin/pinentry-qt

    - name: Docker - setup apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Docker - setup apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian buster stable

    - name: Docker - install
      apt:
        pkg: docker-ce

    - name: Docker - add users to docker group
      with_items: "{{ users }}"
      user:
        name: "{{ item }}"
        groups: docker
        append: yes

    - name: VS Code - setup apt key
      apt_key:
        url:  https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: VS Code - setup apt repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main

    - name: VS Code - install
      apt:
        pkg: code
