- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Install packages
      apt:
        pkg:
          # Base
          - tmux
          - zsh
          - git
          - vim-nox
          - ripgrep
          - fd-find
          - fzf
          - pv

          # Data processing
          - jq

          # Cloud
          - awscli

          # TUI
          - tig

          # Crypto
          - ssh
          - openvpn
          - gnupg

          # Troubleshooting - general
          - strace
          - lsof
          - htop
          - dstat
          - iotop
          - iftop
          - sysstat # sar, pidstat, iostat, mpstat
          - linux-perf

          # Troubleshooting - network
          - tcpdump
          - wireshark
          - mtr
          - ngrep
          - nmap
          - ncat
          - dnsutils # dig
          - net-tools # netstat
          - whois

    - name: Docker - setup apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Docker - setup apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian stretch stable

    - name: Docker - install
      apt:
        pkg: docker-ce

    - name: Docker - add users to docker group
      with_items: "{{ users }}"
      user:
        name: "{{ item }}"
        groups: docker
        append: yes

    - name: VS Code - setup apt key
      apt_key:
        url:  https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: VS Code - setup apt repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main

    - name: VS Code - install
      apt:
        pkg: code
