- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Install packages
      apt:
        pkg:
          # Base
          - tmux
          - zsh
          - vim-nox
          - git
          - tig
          - ripgrep
          - fd-find
          - fzf
          - jq
          - pv
          
          # Crypto
          - openvpn
          - openssh-client
          - gnupg
          - pinentry-tty

          # DB clients
          - postgresql-client
          - default-mysql-client

          # HTTP clients
          - wget
          - curl

          # Cloud
          - rclone
          - awscli

          # Troubleshooting - general
          - sysstat # sar/pidstat/...
          - linux-perf
          - bpfcc-tools
          - strace
          - lsof
          - iftop
          - htop

          # Troubleshooting - network
          - tcpdump
          - wireshark
          - mtr
          - ngrep
          - nmap
          - ncat
          - dnsutils # dig
          - net-tools # netstat
          - whois

    - name: GPG - pinentry-tty as default
      alternatives:
        name: pinentry
        path: /usr/bin/pinentry-tty

    - name: Docker - setup apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Docker - setup apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian buster stable

    - name: Docker - install
      apt:
        pkg: docker-ce

    - name: Docker - add users to docker group
      with_items: "{{ users }}"
      user:
        name: "{{ item }}"
        groups: docker
        append: yes

    - name: VS Code - setup apt key
      apt_key:
        url:  https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: VS Code - setup apt repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main

    - name: VS Code - install
      apt:
        pkg: code
