- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Install packages
      apt: pkg={{item}}
      with_items:
        # Base
        - tmux
        - zsh
        - pv
        - git
        - tig
        - silversearcher-ag
        - awscli
        - emacs25
        - emacs25-common-non-dfsg # emacs info documentation

        # Build environment
        - build-essential
        - autoconf

        # Headers for common libraries
        # many Python/Ruby/Node/etc packages will require some of those
        - libpng-dev

        # Troubleshooting - general
        - gdb
        - strace
        - lsof
        - htop
        - dstat
        - iotop
        - iftop
        - sysstat # sar, pidstat, iostat, mpstat
        - linux-perf

        # Troubleshooting - network
        - tcpdump
        - mtr
        - ngrep
        - nmap # ncat
        - dnsutils # dig
        - net-tools # netstat

    - name: Add users to groups
      with_items: users
      user:
        name: "{{ item }}"
        groups: docker

    - name: Docker - setup apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Docker - setup apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian stretch stable

    - name: Docker - install
      apt:
        pkg: docker-ce
