- hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - name: Install packages
      apt:
        pkg:
          # Base
          - tmux
          - zsh
          - pv
          - git
          - tig
          - ripgrep
          - fd-find
          - jq
          - awscli
          - neovim

          # Crypto
          - ssh
          - openvpn
          - gnupg

          # Troubleshooting - general
          - strace
          - lsof
          - htop
          - dstat
          - iotop
          - iftop
          - sysstat # sar, pidstat, iostat, mpstat
          - linux-perf

          # Troubleshooting - network
          - tcpdump
          - mtr
          - ngrep
          - nmap
          - ncat
          - dnsutils # dig
          - net-tools # netstat

    - name: Docker - setup apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Docker - setup apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian stretch stable

    - name: Docker - install
      apt:
        pkg: docker-ce

    - name: Docker - add users to docker group
      with_items: "{{ users }}"
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
